"""
Sales Report Generator
----------------------
Reads sales data from a CSV file, processes it and generates
a formatted text report with statistics and product breakdown.

Author: Marco
"""

import csv
from datetime import datetime


# ──────────────────────────────────────────────
# 1. LOAD DATA
# ──────────────────────────────────────────────

def load_sales(filepath: str) -> list[dict]:
    """Reads vendas.csv and returns a list of dicts with converted types."""
    sales = []

    with open(filepath, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            sales.append({
                "Produto":    row["Produto"].strip(),
                "Quantidade": int(row["Quantidade"]),
                "Preco":      float(row["Preco"]),
                "Data":       row["Data"].strip(),
            })

    return sales


# ──────────────────────────────────────────────
# 2. VALIDATE DATA
# ──────────────────────────────────────────────

def validate_sales(sales: list[dict]) -> None:
    """
    Checks for basic data integrity issues.
    Raises ValueError if anything is wrong.
    """
    if not sales:
        raise ValueError("The sales list is empty — nothing to process.")

    for i, sale in enumerate(sales, start=2):   # start=2 → skips header row
        if not sale["Produto"]:
            raise ValueError(f"Row {i}: 'Produto' is empty.")
        if sale["Quantidade"] <= 0:
            raise ValueError(f"Row {i}: 'Quantidade' must be > 0 (got {sale['Quantidade']}).")
        if sale["Preco"] <= 0:
            raise ValueError(f"Row {i}: 'Preco' must be > 0 (got {sale['Preco']}).")


# ──────────────────────────────────────────────
# 3. CALCULATE TOTALS & STATISTICS
# ──────────────────────────────────────────────

def calculate_totals(sales: list[dict]) -> tuple[list[dict], dict]:
    """
    Adds a 'ValorTotal' key to each sale and returns
    overall summary statistics.
    """
    enriched = [
        {**sale, "ValorTotal": sale["Quantidade"] * sale["Preco"]}
        for sale in sales
    ]

    total_records  = len(enriched)
    total_units    = sum(s["Quantidade"]  for s in enriched)
    total_revenue  = sum(s["ValorTotal"]  for s in enriched)
    average_ticket = total_revenue / total_records

    stats = {
        "total_records":  total_records,
        "total_units":    total_units,
        "total_revenue":  total_revenue,
        "average_ticket": average_ticket,
    }

    return enriched, stats


# ──────────────────────────────────────────────
# 4. GROUP BY PRODUCT
# ──────────────────────────────────────────────

def group_by_product(sales: list[dict]) -> dict:
    """
    Aggregates sales by product name.
    Returns a dict: { product_name: { "quantity": int, "revenue": float } }
    """
    grouped = {}

    for sale in sales:
        name = sale["Produto"]
        if name not in grouped:
            grouped[name] = {"quantity": 0, "revenue": 0.0}
        grouped[name]["quantity"] += sale["Quantidade"]
        grouped[name]["revenue"]  += sale["ValorTotal"]

    return grouped


def find_highlights(grouped: dict) -> tuple[str, str]:
    """
    Returns the product with the highest quantity sold
    and the product with the highest total revenue.
    (No lambda used — manual loop instead.)
    """
    best_qty_name     = None
    best_qty_value    = -1
    best_rev_name     = None
    best_rev_value    = -1.0

    for name, data in grouped.items():
        if data["quantity"] > best_qty_value:
            best_qty_value = data["quantity"]
            best_qty_name  = name
        if data["revenue"] > best_rev_value:
            best_rev_value = data["revenue"]
            best_rev_name  = name

    return best_qty_name, best_rev_name


# ──────────────────────────────────────────────
# 5. BUILD REPORT
# ──────────────────────────────────────────────

def build_report(stats: dict, grouped: dict, top_qty: str, top_rev: str) -> str:
    """Assembles the full report as a single formatted string."""
    now = datetime.now().strftime("%d/%m/%Y %H:%M")
    lines = []

    # Header
    lines.append("=" * 52)
    lines.append("         SALES REPORT — GENERATED BY PYTHON")
    lines.append(f"         {now}")
    lines.append("=" * 52)
    lines.append("")

    # General stats
    lines.append("[ GENERAL STATISTICS ]")
    lines.append(f"  Total records  : {stats['total_records']}")
    lines.append(f"  Total units    : {stats['total_units']}")
    lines.append(f"  Total revenue  : R$ {stats['total_revenue']:,.2f}")
    lines.append(f"  Average ticket : R$ {stats['average_ticket']:,.2f}")
    lines.append("")

    # Highlights
    lines.append("[ HIGHLIGHTS ]")
    lines.append(f"  Best seller (qty) : {top_qty}  "
                 f"({grouped[top_qty]['quantity']} units)")
    lines.append(f"  Top revenue       : {top_rev}  "
                 f"(R$ {grouped[top_rev]['revenue']:,.2f})")
    lines.append("")

    # Product breakdown — sorted by revenue descending
    lines.append("[ PRODUCT BREAKDOWN ]")
    lines.append(f"  {'Product':<12}  {'Units':>6}  {'Revenue':>14}")
    lines.append(f"  {'-'*12}  {'-'*6}  {'-'*14}")

    sorted_products = sorted(
        grouped.items(),
        key=lambda item: item[1]["revenue"],
        reverse=True
    )

    for name, data in sorted_products:
        lines.append(
            f"  {name:<12}  {data['quantity']:>6}  "
            f"R$ {data['revenue']:>11,.2f}"
        )

    lines.append("")
    lines.append("=" * 52)
    lines.append("  End of report.")
    lines.append("=" * 52)

    return "\n".join(lines)


# ──────────────────────────────────────────────
# 6. SAVE REPORT
# ──────────────────────────────────────────────

def save_report(report: str, filepath: str) -> None:
    """Writes the report string to a .txt file."""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"Report saved to: {filepath}")


# ──────────────────────────────────────────────
# PIPELINE
# ──────────────────────────────────────────────

def main():
    input_path  = "data/vendas.csv"
    output_path = "output/relatorio_vendas.txt"

    # Step 1 — Load
    print("Loading data...")
    sales = load_sales(input_path)

    # Step 2 — Validate
    print("Validating data...")
    validate_sales(sales)

    # Step 3 — Calculate
    print("Calculating totals...")
    enriched_sales, stats = calculate_totals(sales)

    # Step 4 — Group & highlights
    print("Grouping by product...")
    grouped  = group_by_product(enriched_sales)
    top_qty, top_rev = find_highlights(grouped)

    # Step 5 — Build report
    print("Building report...")
    report = build_report(stats, grouped, top_qty, top_rev)

    # Preview
    print("\n--- PREVIEW (first 20 lines) ---")
    for line in report.split("\n")[:20]:
        print(line)
    print("...")

    # Step 6 — Save
    save_report(report, output_path)


if __name__ == "__main__":
    main()
